name: Scheduled Upstream Sync

on:
  schedule:
    - cron:  '0 0 * * *' # Runs every day at midnight (UTC)
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    # Step 1: Checkout your fork
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main # Change this to 'master' if your branch is named that

    # Step 2: Use a sync action
    - name: Sync upstream changes
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: The-Graft-Project/homebrew-tap
        upstream_sync_branch: main
